In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
data = 'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv'
df = pd.read_csv(data)
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

# Data Preparation

In [3]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [8]:
df = df.fillna(0)
df.isnull().sum()

model_year             0
origin                 0
fuel_type              0
drivetrain             0
num_doors              0
engine_displacement    0
num_cylinders          0
horsepower             0
vehicle_weight         0
acceleration           0
fuel_efficiency_mpg    0
dtype: int64

In [17]:
# Split
from sklearn.model_selection import train_test_split

df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(
    df_full_train, test_size=0.25, random_state=1
)

In [18]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [19]:
y_train = df_train['fuel_efficiency_mpg'].values
y_val = df_val['fuel_efficiency_mpg'].values
y_test = df_test['fuel_efficiency_mpg'].values

In [20]:
del df_train['fuel_efficiency_mpg']
del df_val['fuel_efficiency_mpg']
del df_test['fuel_efficiency_mpg']

# Question 1

In [36]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.feature_extraction import DictVectorizer
from sklearn.metrics import roc_auc_score
from sklearn.tree import export_text

In [34]:
train_dicts = df_train.fillna(0).to_dict(orient='records')

dv = DictVectorizer(sparse = True)
X_train = dv.fit_transform(train_dicts)

In [43]:
val_dicts = df_val.to_dict(orient='records')
X_val = dv.transform(val_dicts)

In [37]:
dt = DecisionTreeRegressor(max_depth=1)
dt.fit(X_train,y_train)

DecisionTreeRegressor(max_depth=1)

In [38]:
print(export_text(dt, feature_names=list(dv.get_feature_names_out())))

|--- model_year <= 1997.50
|   |--- value: [28.61]
|--- model_year >  1997.50
|   |--- value: [31.17]

# Question 2

In [39]:
from sklearn.ensemble import RandomForestRegressor

In [54]:
rf = RandomForestRegressor(
        n_estimators=10,
        random_state=1,
        n_jobs=-1
)

rf.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, n_jobs=-1, random_state=1)

In [55]:
y_pred =  rf.predict(X_val)
RMSE = np.sqrt(np.mean(np.square(y_pred-y_val))).item()
RMSE

1.8332197358745623

# Question 3

In [57]:
scores = []
for e in [10,50,100,150]:
    rf = RandomForestRegressor(
        n_estimators=e,
        random_state=1,
        n_jobs=-1
        )

    rf.fit(X_train, y_train)

    y_pred =  rf.predict(X_val)
    RMSE = round(np.sqrt(np.mean(np.square(y_pred-y_val))).item(),3)

    scores.append((e,RMSE))

scores

[(10, 1.833), (50, 1.774), (100, 1.77), (150, 1.769)]

# Question 4

In [61]:
scores = []
for m in [10,15,20,25]:
    m_scores = []
    for e in [10,50,100,150]:
        rf = RandomForestRegressor(
            max_depth=m,
            n_estimators=e,
            random_state=1,
            n_jobs=-1
            )

        rf.fit(X_train, y_train)

        y_pred =  rf.predict(X_val)
        RMSE = np.sqrt(np.mean(np.square(y_pred-y_val))).item()

        # print(m,",",e,": ",RMSE)

        m_scores.append(RMSE)

    scores.append((m,np.mean(m_scores)))

scores

[(10, np.float64(1.7543924943801008)),
 (15, np.float64(1.7842243445385957)),
 (20, np.float64(1.7867711878395158)),
 (25, np.float64(1.7863054936840876))]

# Question 5

In [79]:
rf = RandomForestRegressor(
    max_depth=20,
    n_estimators=10,
    random_state=1,
    n_jobs=-1
    )

rf.fit(X_train, y_train)

df_rf = pd.DataFrame(rf.feature_importances_, index=dv.get_feature_names_out())
df_rf.sort_values(by=[0],ascending=False)

                                     0
model_year                    0.296107
vehicle_weight                0.203313
fuel_type=Gasoline            0.160712
horsepower                    0.078271
engine_displacement           0.061281
acceleration                  0.054998
origin=USA                    0.042152
drivetrain=Front-wheel drive  0.020062
num_doors                     0.019401
fuel_type=Diesel              0.016571
fuel_type=Hybrid              0.016272
drivetrain=All-wheel drive    0.007951
num_cylinders                 0.007318
origin=Asia                   0.006515
drivetrain=Rear-wheel drive   0.005638
origin=Europe                 0.003436

# Question 6

In [80]:
# install xgboost
!pip install xgboost

Requirement already satisfied: xgboost in C:\Users\fprh6\Documents\personal_projects\01_Study\ZOOMCAMP\.venv\Lib\site-packages (3.2.0)
Requirement already satisfied: numpy in C:\Users\fprh6\Documents\personal_projects\01_Study\ZOOMCAMP\.venv\Lib\site-packages (from xgboost) (2.4.6)
Requirement already satisfied: scipy in C:\Users\fprh6\Documents\personal_projects\01_Study\ZOOMCAMP\.venv\Lib\site-packages (from xgboost) (1.17.1)

In [81]:
import xgboost as xgb

In [82]:
features = list(dv.get_feature_names_out())
dtrain = xgb.DMatrix(X_train, label = y_train, feature_names = features)
dval = xgb.DMatrix(X_val, label = y_val, feature_names = features)

In [83]:
watchlist = [(dtrain,'train'),(dval,"val")]

In [95]:
%%capture output 
# for eta 0.3

xgb_params = {
    'eta': 0.3, 
    'max_depth': 6,
    'min_child_weight': 1,
    
    'objective': 'reg:squarederror',
    'nthread': 8,
    
    'seed': 1,
    'verbosity': 1,
}

model = xgb.train(xgb_params, dtrain, num_boost_round=100, evals=watchlist)

In [96]:
score = []
for line in output.stdout.strip().split("\n"):
    case, train, val = line.split("\t")
    val_rmse = float(val.split(":")[1])
    score.append(val_rmse)

np.mean(score)

np.float64(1.7929225)

In [97]:
%%capture output 
# for eta 0.1

xgb_params = {
    'eta': 0.1, 
    'max_depth': 6,
    'min_child_weight': 1,
    
    'objective': 'reg:squarederror',
    'nthread': 8,
    
    'seed': 1,
    'verbosity': 1,
}

model = xgb.train(xgb_params, dtrain, num_boost_round=100, evals=watchlist)

In [98]:
score = []
for line in output.stdout.strip().split("\n"):
    case, train, val = line.split("\t")
    val_rmse = float(val.split(":")[1])
    score.append(val_rmse)

np.mean(score)

np.float64(1.7881036000000001)